### ISSUE TITLE
need to report which file failed; weird typedef problem

### ISSUE THREAD

**Issue by Laeeth** [atilaneves/include#2]
1.  currently when it fails on an assert it doesn't tell you which source file failed.  it would be nice to know.

2. converting libzfs, it chokes on /usr/include/libspl/sys/frame.h (to find the problem I had to grep for the offending typedef).
typedefs should only have 1 member, not 2
Cursor(TypedefDecl, "gregset_t", Type(Typedef, "gregset_t"))
[Cursor(TypeRef, "greg_t", Type(Typedef, "greg_t")), Cursor(IntegerLiteral, "", Type(Int, "int"))]

Here is the offending code:
#if defined(_LP64) || defined(_I32LPx)
typedef long    greg_t;
#else
typedef int     greg_t;
#endif

Bizarrely, it chokes even if I hack the source by doing:
# FIXME
#define _LP64 1

just before the code.

`
laeeth@sheldrake> C_INCLUDE_PATH=/usr/include/libspl:/usr/include/libzfs /tank2/develop/include/bin/include libzfs.h /tank2/develop/include/libzfs/libzfs.di

typedefs should only have 1 member, not 2
Cursor(TypedefDecl, "gregset_t", Type(Typedef, "gregset_t"))
[Cursor(TypeRef, "greg_t", Type(Typedef, "greg_t")), Cursor(IntegerLiteral, "", Type(Int, "int"))]
`

If I hack the include D code by doing the following then it continues on its merry way and appears to finish.  The resulting D source doesn't compile yet, but that's probably for other reasons.

You might want to have a treat errors as warnings command-line switch, because in the general case it's more than  occasionally much better to do most of the job than just fail.  Maybe you could add // FIXME: message to the resulting source.

source/include/translation/typedef_.d

`

    if(!(children.length == 1 ||
           (children.length == 0 && typedef_.type.kind == Type.Kind.Typedef)))
    {
            import std.stdio:writeln;
           writeln(text("typedefs should only have 1 member, not ", children.length, "\n", typedef_, "\n", children));
    }

`

**Comment by atilaneves** [comment]
These are two issues. Please open a different Github issue for each problem. I'm closing this and opening two.

**Comment by atilaneves** [comment]
@Laeeth See #13 and #14
